name: tmdb_favorites
description: A simple list of the TMDB top 20 rated movies.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  http: ^0.13.4
  path_provider: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
