name: tmdb_favorites
description: A simple list of the TMDB top 20 rated movies.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_file_store: ^1.1.0
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
